import networkx as nx
G = nx.Graph()
G.add_node(1, depth=0)
G.add_node(2, depth=1)
G.add_edge(1, 2)
G.add_edge(2, 3)
G.add_node(4, filetype="pdf", depth=3)
G.add_edge(3, 4)
G.add_edge(4, 5)
nx.write_graphml(G, 'graph.graphml')